### ISSUE TITLE
Unique and only specified fields in .find()

### ISSUE THREAD

**Issue by morfair** [bmuller/twistar#57]
How can I get only specified fields in .find() method? Can I get only unique rows?

**Comment by bmuller** [comment]
You cannot specify the fields you want in [find](http://findingscience.com/twistar/apidoc/twistar.dbobject.DBObject.html#find).  What is returned is an object containing properties for all of the fields.  Since twistar is an ORM, every row should be unique (because each row will have either a unique ID or it will be a join table with unique combos of IDs).

I'm happy to answer any other questions you have - feel free to email me at the address listed on my profile page.

**Comment by morfair** [comment]
@bmuller 
I mean how to do "SELECT DISTINCT(column) ..."
